-- =====================================================================
--  001_Seed_RBAC.sql  (sinh từ danh sách API trong Docs/openapi.yaml; sau này sửa tay được)
--  Chạy SAU 000_RelationshipTable.sql.
--  Nội dung: 3 vai trò mặc định, permissions, api_endpoints, ánh xạ
--  permissions_endpoints, role_permissions, tài khoản admin đầu tiên.
--  Middleware: so khớp (method, path pattern) -> api_endpoints; nếu is_public=1 thì bỏ qua;
--  ngược lại user.role_id phải có permission gắn với endpoint đó (role_permissions ->
--  permissions_endpoints), nếu không trả 403/3101 (hoặc 3102/3103/3104 theo vai trò yêu cầu).
--  Có thể chỉnh quyền sau bằng các API /role_permissions, /permission_endpoints.
-- =====================================================================
BEGIN;

INSERT INTO roles (name, description) VALUES
  ('admin',   'Quản trị viên hệ thống'),
  ('doctor',  'Bác sĩ (nhân viên y tế)'),
  ('patient', 'Bệnh nhân')
ON CONFLICT (name) DO NOTHING;

INSERT INTO permissions (name, description) VALUES
  ('answer_image.create', 'answer image / create'),
  ('answer_image.delete', 'answer image / delete'),
  ('answer_image.read', 'answer image / read'),
  ('api_endpoint.create', 'api endpoint / create'),
  ('api_endpoint.delete', 'api endpoint / delete'),
  ('api_endpoint.list', 'api endpoint / list'),
  ('api_endpoint.update', 'api endpoint / update'),
  ('auth.change_password', 'auth / change password'),
  ('auth.create_staff', 'auth / create staff'),
  ('auth.session', 'auth / session'),
  ('branch.create', 'branch / create'),
  ('branch.delete', 'branch / delete'),
  ('branch.read', 'branch / read'),
  ('branch.update', 'branch / update'),
  ('department.create', 'department / create'),
  ('department.delete', 'department / delete'),
  ('department.read', 'department / read'),
  ('department.update', 'department / update'),
  ('doctor_patient.create', 'doctor patient / create'),
  ('doctor_patient.search', 'doctor patient / search'),
  ('lab_request.create', 'lab request / create'),
  ('lab_result.read', 'lab result / read'),
  ('lab_result.write', 'lab result / write'),
  ('lesion_episode.create', 'lesion episode / create'),
  ('lesion_episode.delete', 'lesion episode / delete'),
  ('lesion_episode.read', 'lesion episode / read'),
  ('lesion_episode.read_own', 'lesion episode / read own'),
  ('lesion_episode.read_record', 'lesion episode / read record'),
  ('lesion_episode.update', 'lesion episode / update'),
  ('lesion_location.create', 'lesion location / create'),
  ('lesion_location.delete', 'lesion location / delete'),
  ('lesion_location.read', 'lesion location / read'),
  ('lesion_location.update', 'lesion location / update'),
  ('lesion_photo.create', 'lesion photo / create'),
  ('lesion_photo.delete', 'lesion photo / delete'),
  ('lesion_photo.read', 'lesion photo / read'),
  ('lesion_photo.update', 'lesion photo / update'),
  ('media.delete', 'media / delete'),
  ('media.read', 'media / read'),
  ('media.upload', 'media / upload'),
  ('medical_record.accept', 'medical record / accept'),
  ('medical_record.answer.read', 'medical record / answer / read'),
  ('medical_record.answer.write', 'medical record / answer / write'),
  ('medical_record.classify', 'medical record / classify'),
  ('medical_record.complete', 'medical record / complete'),
  ('medical_record.create', 'medical record / create'),
  ('medical_record.delete', 'medical record / delete'),
  ('medical_record.history', 'medical record / history'),
  ('medical_record.list', 'medical record / list'),
  ('medical_record.read', 'medical record / read'),
  ('permission.create', 'permission / create'),
  ('permission.delete', 'permission / delete'),
  ('permission.list', 'permission / list'),
  ('permission.update', 'permission / update'),
  ('permission_endpoint.assign', 'permission endpoint / assign'),
  ('permission_endpoint.read', 'permission endpoint / read'),
  ('permission_endpoint.revoke', 'permission endpoint / revoke'),
  ('prescription.create', 'prescription / create'),
  ('prescription.read', 'prescription / read'),
  ('profile.read', 'profile / read'),
  ('profile.update', 'profile / update'),
  ('role.create', 'role / create'),
  ('role.delete', 'role / delete'),
  ('role.list', 'role / list'),
  ('role.update', 'role / update'),
  ('role_permission.assign', 'role permission / assign'),
  ('role_permission.read', 'role permission / read'),
  ('role_permission.revoke', 'role permission / revoke'),
  ('room.create', 'room / create'),
  ('room.delete', 'room / delete'),
  ('room.read', 'room / read'),
  ('room.update', 'room / update'),
  ('template.create', 'template / create'),
  ('template.delete', 'template / delete'),
  ('template.question.create', 'template / question / create'),
  ('template.question.delete', 'template / question / delete'),
  ('template.question.update', 'template / question / update'),
  ('template.read', 'template / read'),
  ('template.section.create', 'template / section / create'),
  ('template.section.delete', 'template / section / delete'),
  ('template.section.update', 'template / section / update'),
  ('template.update', 'template / update'),
  ('uas7.create', 'uas7 / create'),
  ('uas7.eligibility', 'uas7 / eligibility'),
  ('uas7.read', 'uas7 / read'),
  ('user.assign', 'user / assign'),
  ('user.create', 'user / create'),
  ('user.delete', 'user / delete'),
  ('user.list', 'user / list'),
  ('user.read', 'user / read'),
  ('user.update', 'user / update')
ON CONFLICT (name) DO NOTHING;

INSERT INTO api_endpoints (name, method, path, description, is_public) VALUES
  ('signup', 'POST', '/api/v1/auth/signup', 'Đăng ký tài khoản bệnh nhân', 1),
  ('login', 'POST', '/api/v1/auth/login', 'Đăng nhập', 1),
  ('logout', 'POST', '/api/v1/auth/logout', 'Đăng xuất', 0),
  ('forgotPassword', 'POST', '/api/v1/auth/forgot-password', 'Quên mật khẩu - gửi OTP', 1),
  ('resetPassword', 'POST', '/api/v1/auth/reset-password', 'Đặt lại mật khẩu bằng OTP', 1),
  ('changePassword', 'PUT', '/api/v1/auth/change-password', 'Đổi mật khẩu', 0),
  ('adminCreateStaff', 'POST', '/api/v1/auth/admin/create-staff', 'Admin tạo tài khoản nhân viên', 0),
  ('getProfile', 'GET', '/api/v1/profile', 'Xem hồ sơ cá nhân', 0),
  ('updateProfile', 'PUT', '/api/v1/profile', 'Cập nhật hồ sơ cá nhân', 0),
  ('adminCreateUser', 'POST', '/api/v1/admin/users', 'Admin tạo người dùng', 0),
  ('adminListUsers', 'GET', '/api/v1/admin/users', 'Danh sách người dùng', 0),
  ('adminGetUser', 'GET', '/api/v1/admin/users/:id', 'Chi tiết người dùng', 0),
  ('adminUpdateUser', 'PUT', '/api/v1/admin/users/:id', 'Cập nhật người dùng (khoá/mở, đổi vai trò)', 0),
  ('adminDeleteUser', 'DELETE', '/api/v1/admin/users/:id', 'Xoá người dùng', 0),
  ('adminAssignStaff', 'PUT', '/api/v1/admin/users/:id/assign', 'Gán nhân viên vào chi nhánh/khoa/phòng', 0),
  ('createRole', 'POST', '/api/v1/roles', 'Tạo vai trò', 0),
  ('listRoles', 'GET', '/api/v1/roles', 'Danh sách vai trò', 0),
  ('updateRole', 'PUT', '/api/v1/roles/:id', 'Cập nhật vai trò', 0),
  ('deleteRole', 'DELETE', '/api/v1/roles/:id', 'Xoá vai trò', 0),
  ('createPermission', 'POST', '/api/v1/permissions', 'Tạo quyền', 0),
  ('listPermissions', 'GET', '/api/v1/permissions', 'Danh sách quyền', 0),
  ('updatePermission', 'PUT', '/api/v1/permissions/:id', 'Cập nhật quyền', 0),
  ('deletePermission', 'DELETE', '/api/v1/permissions/:id', 'Xoá quyền', 0),
  ('assignRolePermissions', 'POST', '/api/v1/role_permissions', 'Gán quyền cho vai trò', 0),
  ('getRolePermissions', 'GET', '/api/v1/role_permissions/role/:role_id', 'Xem quyền của vai trò', 0),
  ('revokeRolePermission', 'DELETE', '/api/v1/role_permissions/role/:role_id/permission/:permission_id', 'Thu hồi 1 quyền khỏi vai trò', 0),
  ('createApiEndpoint', 'POST', '/api/v1/api_endpoints', 'Đăng ký API vào danh mục', 0),
  ('listApiEndpoints', 'GET', '/api/v1/api_endpoints', 'Danh sách API trong danh mục', 0),
  ('updateApiEndpoint', 'PUT', '/api/v1/api_endpoints/:id', 'Cập nhật API trong danh mục', 0),
  ('deleteApiEndpoint', 'DELETE', '/api/v1/api_endpoints/:id', 'Xoá API khỏi danh mục', 0),
  ('assignPermissionEndpoints', 'POST', '/api/v1/permission_endpoints', 'Gán API cho quyền', 0),
  ('getPermissionEndpoints', 'GET', '/api/v1/permission_endpoints/permission/:permission_id', 'Xem các API của một quyền', 0),
  ('revokePermissionEndpoint', 'DELETE', '/api/v1/permission_endpoints/permission/:permission_id/endpoint/:endpoint_id', 'Thu hồi 1 API khỏi quyền', 0),
  ('createBranch', 'POST', '/api/v1/branches', 'Tạo chi nhánh', 0),
  ('listBranches', 'GET', '/api/v1/branches', 'Danh sách chi nhánh', 0),
  ('getBranch', 'GET', '/api/v1/branches/:id', 'Chi tiết chi nhánh', 0),
  ('updateBranch', 'PUT', '/api/v1/branches/:id', 'Cập nhật chi nhánh', 0),
  ('deleteBranch', 'DELETE', '/api/v1/branches/:id', 'Xoá chi nhánh', 0),
  ('createDepartment', 'POST', '/api/v1/departments', 'Tạo khoa', 0),
  ('listDepartments', 'GET', '/api/v1/departments', 'Danh sách khoa', 0),
  ('getDepartment', 'GET', '/api/v1/departments/:id', 'Chi tiết khoa', 0),
  ('updateDepartment', 'PUT', '/api/v1/departments/:id', 'Cập nhật khoa', 0),
  ('deleteDepartment', 'DELETE', '/api/v1/departments/:id', 'Xoá khoa', 0),
  ('createRoom', 'POST', '/api/v1/rooms', 'Tạo phòng', 0),
  ('listRooms', 'GET', '/api/v1/rooms', 'Danh sách phòng', 0),
  ('getRoom', 'GET', '/api/v1/rooms/:id', 'Chi tiết phòng', 0),
  ('updateRoom', 'PUT', '/api/v1/rooms/:id', 'Cập nhật phòng', 0),
  ('deleteRoom', 'DELETE', '/api/v1/rooms/:id', 'Xoá phòng', 0),
  ('doctorSearchPatients', 'GET', '/api/v1/doctor/patients/search', 'Bác sĩ tìm bệnh nhân', 0),
  ('doctorCreatePatient', 'POST', '/api/v1/doctor/patients', 'Bác sĩ tạo hồ sơ bệnh nhân', 0),
  ('createTemplate', 'POST', '/api/v1/templates', 'Tạo template', 0),
  ('listTemplates', 'GET', '/api/v1/templates/all', 'Danh sách template', 0),
  ('getTemplate', 'GET', '/api/v1/templates/:id', 'Chi tiết template (lồng section → question → option)', 0),
  ('updateTemplate', 'PUT', '/api/v1/templates/:id', 'Cập nhật template', 0),
  ('deleteTemplate', 'DELETE', '/api/v1/templates/:id', 'Xoá template', 0),
  ('createSection', 'POST', '/api/v1/templates/:template_id/sections', 'Thêm section', 0),
  ('updateSection', 'PUT', '/api/v1/templates/sections/:id', 'Cập nhật section', 0),
  ('deleteSection', 'DELETE', '/api/v1/templates/sections/:id', 'Xoá section', 0),
  ('createQuestion', 'POST', '/api/v1/templates/sections/:section_id/questions', 'Thêm câu hỏi (kèm options)', 0),
  ('updateQuestion', 'PUT', '/api/v1/templates/questions/:id', 'Cập nhật câu hỏi (upsert options)', 0),
  ('deleteQuestion', 'DELETE', '/api/v1/templates/questions/:id', 'Xoá câu hỏi', 0),
  ('getClassifyQuestions', 'GET', '/api/v1/medical_records/classify-questions', 'Lấy bộ câu hỏi phân loại (chọn template)', 0),
  ('classifyMedicalRecord', 'POST', '/api/v1/medical_records/classify', 'Phân loại → template phù hợp', 0),
  ('createMedicalRecord', 'POST', '/api/v1/medical_records', 'Tạo bệnh án', 0),
  ('listMedicalRecords', 'GET', '/api/v1/medical_records/all', 'Danh sách bệnh án (bác sĩ/admin)', 0),
  ('getMedicalRecord', 'GET', '/api/v1/medical_records/:id', 'Chi tiết bệnh án', 0),
  ('getMedicalRecordSummary', 'GET', '/api/v1/medical_records/:id/summary', 'Tóm tắt bệnh án', 0),
  ('getPatientHistory', 'GET', '/api/v1/medical_records/patients/:id/history', 'Lịch sử khám của bệnh nhân', 0),
  ('acceptMedicalRecord', 'POST', '/api/v1/medical_records/:id/accept', 'Bác sĩ nhận bệnh án', 0),
  ('completeMedicalRecord', 'PUT', '/api/v1/medical_records/:id', 'Bác sĩ chốt bệnh án (completed)', 0),
  ('deleteMedicalRecord', 'DELETE', '/api/v1/medical_records/:id', 'Admin xoá bệnh án', 0),
  ('getAnswers', 'GET', '/api/v1/medical_records/:id/answers', 'Danh sách câu trả lời của bệnh án', 0),
  ('upsertAnswers', 'PUT', '/api/v1/medical_records/:id/answers', 'Lưu/cập nhật câu trả lời (upsert)', 0),
  ('uploadImage', 'POST', '/api/v1/image-attachments/upload', 'Upload 1 ảnh', 0),
  ('uploadImages', 'POST', '/api/v1/image-attachments/upload-multiple', 'Upload nhiều ảnh (tối đa 10)', 0),
  ('listUserImages', 'GET', '/api/v1/image-attachments/user/:user_id', 'Danh sách ảnh của người dùng', 0),
  ('deleteImage', 'DELETE', '/api/v1/image-attachments/:id', 'Xoá ảnh', 0),
  ('linkAnswerImage', 'POST', '/api/v1/answer-images', 'Gắn ảnh vào câu trả lời', 0),
  ('listAnswerImages', 'GET', '/api/v1/answer-images/:answer_id', 'Ảnh của một câu trả lời', 0),
  ('unlinkAnswerImage', 'DELETE', '/api/v1/answer-images/:id', 'Gỡ liên kết ảnh khỏi câu trả lời', 0),
  ('createLesionEpisode', 'POST', '/api/v1/lesion-episodes', 'Tạo đợt tổn thương', 0),
  ('listMyLesionEpisodes', 'GET', '/api/v1/lesion-episodes/my', 'Đợt tổn thương của tôi', 0),
  ('listLesionEpisodesByRecord', 'GET', '/api/v1/lesion-episodes/record/:medical_record_id', 'Đợt tổn thương theo bệnh án (bác sĩ)', 0),
  ('getLesionEpisode', 'GET', '/api/v1/lesion-episodes/:id', 'Chi tiết đợt tổn thương', 0),
  ('updateLesionEpisode', 'PATCH', '/api/v1/lesion-episodes/:id', 'Cập nhật đợt tổn thương', 0),
  ('deleteLesionEpisode', 'DELETE', '/api/v1/lesion-episodes/:id', 'Xoá đợt tổn thương', 0),
  ('createLesionLocation', 'POST', '/api/v1/lesion-locations', 'Thêm vị trí tổn thương', 0),
  ('listLesionLocations', 'GET', '/api/v1/lesion-locations/episode/:episode_id', 'Vị trí của một đợt', 0),
  ('updateLesionLocation', 'PATCH', '/api/v1/lesion-locations/:id', 'Cập nhật vị trí', 0),
  ('deleteLesionLocation', 'DELETE', '/api/v1/lesion-locations/:id', 'Xoá vị trí', 0),
  ('createLesionPhoto', 'POST', '/api/v1/lesion-photos', 'Thêm ảnh tổn thương', 0),
  ('listLesionPhotosByLocation', 'GET', '/api/v1/lesion-photos/location/:location_id', 'Ảnh theo vị trí', 0),
  ('listLesionPhotosByEpisode', 'GET', '/api/v1/lesion-photos/episode/:episode_id', 'Ảnh theo đợt tổn thương', 0),
  ('updateLesionPhotoMilestone', 'PATCH', '/api/v1/lesion-photos/:id/milestone', 'Cập nhật mốc & điểm của ảnh', 0),
  ('deleteLesionPhoto', 'DELETE', '/api/v1/lesion-photos/:id', 'Xoá ảnh tổn thương', 0),
  ('getUas7Eligibility', 'GET', '/api/v1/uas7-scores/eligibility', 'Kiểm tra bệnh nhân có được chấm UAS7 không', 0),
  ('createUas7Score', 'POST', '/api/v1/uas7-scores', 'Ghi điểm UAS7 của một ngày', 0),
  ('listUas7ByPatient', 'GET', '/api/v1/uas7-scores/patient/:patient_id', 'Lịch sử điểm UAS7 của bệnh nhân', 0),
  ('getUas7Week', 'GET', '/api/v1/uas7-scores/week/:patient_id', 'Tổng điểm UAS7 theo tuần & mức độ', 0),
  ('createPrescription', 'POST', '/api/v1/prescriptions', 'Bác sĩ kê đơn thuốc', 0),
  ('getPrescription', 'GET', '/api/v1/prescriptions/:medical_record_id', 'Xem đơn thuốc của bệnh án', 0),
  ('createLabRequest', 'POST', '/api/v1/lab-requests', 'Bác sĩ chỉ định xét nghiệm', 0),
  ('listLabResults', 'GET', '/api/v1/lab-results/:record_id', 'Xem chỉ định & kết quả xét nghiệm của bệnh án', 0),
  ('enterLabResults', 'POST', '/api/v1/lab-results', 'Bác sĩ nhập kết quả xét nghiệm', 0)
ON CONFLICT (method, path) DO NOTHING;

-- permissions <-> endpoints
INSERT INTO permissions_endpoints (permission_id, endpoint_id)
SELECT p.permission_id, a.endpoint_id FROM (VALUES
  ('auth.session', 'POST', '/api/v1/auth/logout'),
  ('auth.change_password', 'PUT', '/api/v1/auth/change-password'),
  ('auth.create_staff', 'POST', '/api/v1/auth/admin/create-staff'),
  ('profile.read', 'GET', '/api/v1/profile'),
  ('profile.update', 'PUT', '/api/v1/profile'),
  ('user.create', 'POST', '/api/v1/admin/users'),
  ('user.list', 'GET', '/api/v1/admin/users'),
  ('user.read', 'GET', '/api/v1/admin/users/:id'),
  ('user.update', 'PUT', '/api/v1/admin/users/:id'),
  ('user.delete', 'DELETE', '/api/v1/admin/users/:id'),
  ('user.assign', 'PUT', '/api/v1/admin/users/:id/assign'),
  ('role.create', 'POST', '/api/v1/roles'),
  ('role.list', 'GET', '/api/v1/roles'),
  ('role.update', 'PUT', '/api/v1/roles/:id'),
  ('role.delete', 'DELETE', '/api/v1/roles/:id'),
  ('permission.create', 'POST', '/api/v1/permissions'),
  ('permission.list', 'GET', '/api/v1/permissions'),
  ('permission.update', 'PUT', '/api/v1/permissions/:id'),
  ('permission.delete', 'DELETE', '/api/v1/permissions/:id'),
  ('role_permission.assign', 'POST', '/api/v1/role_permissions'),
  ('role_permission.read', 'GET', '/api/v1/role_permissions/role/:role_id'),
  ('role_permission.revoke', 'DELETE', '/api/v1/role_permissions/role/:role_id/permission/:permission_id'),
  ('api_endpoint.create', 'POST', '/api/v1/api_endpoints'),
  ('api_endpoint.list', 'GET', '/api/v1/api_endpoints'),
  ('api_endpoint.update', 'PUT', '/api/v1/api_endpoints/:id'),
  ('api_endpoint.delete', 'DELETE', '/api/v1/api_endpoints/:id'),
  ('permission_endpoint.assign', 'POST', '/api/v1/permission_endpoints'),
  ('permission_endpoint.read', 'GET', '/api/v1/permission_endpoints/permission/:permission_id'),
  ('permission_endpoint.revoke', 'DELETE', '/api/v1/permission_endpoints/permission/:permission_id/endpoint/:endpoint_id'),
  ('branch.create', 'POST', '/api/v1/branches'),
  ('branch.read', 'GET', '/api/v1/branches'),
  ('branch.read', 'GET', '/api/v1/branches/:id'),
  ('branch.update', 'PUT', '/api/v1/branches/:id'),
  ('branch.delete', 'DELETE', '/api/v1/branches/:id'),
  ('department.create', 'POST', '/api/v1/departments'),
  ('department.read', 'GET', '/api/v1/departments'),
  ('department.read', 'GET', '/api/v1/departments/:id'),
  ('department.update', 'PUT', '/api/v1/departments/:id'),
  ('department.delete', 'DELETE', '/api/v1/departments/:id'),
  ('room.create', 'POST', '/api/v1/rooms'),
  ('room.read', 'GET', '/api/v1/rooms'),
  ('room.read', 'GET', '/api/v1/rooms/:id'),
  ('room.update', 'PUT', '/api/v1/rooms/:id'),
  ('room.delete', 'DELETE', '/api/v1/rooms/:id'),
  ('doctor_patient.search', 'GET', '/api/v1/doctor/patients/search'),
  ('doctor_patient.create', 'POST', '/api/v1/doctor/patients'),
  ('template.create', 'POST', '/api/v1/templates'),
  ('template.read', 'GET', '/api/v1/templates/all'),
  ('template.read', 'GET', '/api/v1/templates/:id'),
  ('template.update', 'PUT', '/api/v1/templates/:id'),
  ('template.delete', 'DELETE', '/api/v1/templates/:id'),
  ('template.section.create', 'POST', '/api/v1/templates/:template_id/sections'),
  ('template.section.update', 'PUT', '/api/v1/templates/sections/:id'),
  ('template.section.delete', 'DELETE', '/api/v1/templates/sections/:id'),
  ('template.question.create', 'POST', '/api/v1/templates/sections/:section_id/questions'),
  ('template.question.update', 'PUT', '/api/v1/templates/questions/:id'),
  ('template.question.delete', 'DELETE', '/api/v1/templates/questions/:id'),
  ('medical_record.classify', 'GET', '/api/v1/medical_records/classify-questions'),
  ('medical_record.classify', 'POST', '/api/v1/medical_records/classify'),
  ('medical_record.create', 'POST', '/api/v1/medical_records'),
  ('medical_record.list', 'GET', '/api/v1/medical_records/all'),
  ('medical_record.read', 'GET', '/api/v1/medical_records/:id'),
  ('medical_record.read', 'GET', '/api/v1/medical_records/:id/summary'),
  ('medical_record.history', 'GET', '/api/v1/medical_records/patients/:id/history'),
  ('medical_record.accept', 'POST', '/api/v1/medical_records/:id/accept'),
  ('medical_record.complete', 'PUT', '/api/v1/medical_records/:id'),
  ('medical_record.delete', 'DELETE', '/api/v1/medical_records/:id'),
  ('medical_record.answer.read', 'GET', '/api/v1/medical_records/:id/answers'),
  ('medical_record.answer.write', 'PUT', '/api/v1/medical_records/:id/answers'),
  ('media.upload', 'POST', '/api/v1/image-attachments/upload'),
  ('media.upload', 'POST', '/api/v1/image-attachments/upload-multiple'),
  ('media.read', 'GET', '/api/v1/image-attachments/user/:user_id'),
  ('media.delete', 'DELETE', '/api/v1/image-attachments/:id'),
  ('answer_image.create', 'POST', '/api/v1/answer-images'),
  ('answer_image.read', 'GET', '/api/v1/answer-images/:answer_id'),
  ('answer_image.delete', 'DELETE', '/api/v1/answer-images/:id'),
  ('lesion_episode.create', 'POST', '/api/v1/lesion-episodes'),
  ('lesion_episode.read_own', 'GET', '/api/v1/lesion-episodes/my'),
  ('lesion_episode.read_record', 'GET', '/api/v1/lesion-episodes/record/:medical_record_id'),
  ('lesion_episode.read', 'GET', '/api/v1/lesion-episodes/:id'),
  ('lesion_episode.update', 'PATCH', '/api/v1/lesion-episodes/:id'),
  ('lesion_episode.delete', 'DELETE', '/api/v1/lesion-episodes/:id'),
  ('lesion_location.create', 'POST', '/api/v1/lesion-locations'),
  ('lesion_location.read', 'GET', '/api/v1/lesion-locations/episode/:episode_id'),
  ('lesion_location.update', 'PATCH', '/api/v1/lesion-locations/:id'),
  ('lesion_location.delete', 'DELETE', '/api/v1/lesion-locations/:id'),
  ('lesion_photo.create', 'POST', '/api/v1/lesion-photos'),
  ('lesion_photo.read', 'GET', '/api/v1/lesion-photos/location/:location_id'),
  ('lesion_photo.read', 'GET', '/api/v1/lesion-photos/episode/:episode_id'),
  ('lesion_photo.update', 'PATCH', '/api/v1/lesion-photos/:id/milestone'),
  ('lesion_photo.delete', 'DELETE', '/api/v1/lesion-photos/:id'),
  ('uas7.eligibility', 'GET', '/api/v1/uas7-scores/eligibility'),
  ('uas7.create', 'POST', '/api/v1/uas7-scores'),
  ('uas7.read', 'GET', '/api/v1/uas7-scores/patient/:patient_id'),
  ('uas7.read', 'GET', '/api/v1/uas7-scores/week/:patient_id'),
  ('prescription.create', 'POST', '/api/v1/prescriptions'),
  ('prescription.read', 'GET', '/api/v1/prescriptions/:medical_record_id'),
  ('lab_request.create', 'POST', '/api/v1/lab-requests'),
  ('lab_result.read', 'GET', '/api/v1/lab-results/:record_id'),
  ('lab_result.write', 'POST', '/api/v1/lab-results')
) AS v(perm, method, path)
JOIN permissions p ON p.name = v.perm
JOIN api_endpoints a ON a.method = v.method AND a.path = v.path
ON CONFLICT (permission_id, endpoint_id) DO NOTHING;

-- role <-> permissions
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id FROM (VALUES
  ('doctor', 'answer_image.create'),
  ('patient', 'answer_image.create'),
  ('doctor', 'answer_image.delete'),
  ('patient', 'answer_image.delete'),
  ('admin', 'answer_image.read'),
  ('doctor', 'answer_image.read'),
  ('patient', 'answer_image.read'),
  ('admin', 'api_endpoint.create'),
  ('admin', 'api_endpoint.delete'),
  ('admin', 'api_endpoint.list'),
  ('admin', 'api_endpoint.update'),
  ('admin', 'auth.change_password'),
  ('doctor', 'auth.change_password'),
  ('patient', 'auth.change_password'),
  ('admin', 'auth.create_staff'),
  ('admin', 'auth.session'),
  ('doctor', 'auth.session'),
  ('patient', 'auth.session'),
  ('admin', 'branch.create'),
  ('admin', 'branch.delete'),
  ('admin', 'branch.read'),
  ('doctor', 'branch.read'),
  ('admin', 'branch.update'),
  ('admin', 'department.create'),
  ('admin', 'department.delete'),
  ('admin', 'department.read'),
  ('doctor', 'department.read'),
  ('admin', 'department.update'),
  ('doctor', 'doctor_patient.create'),
  ('doctor', 'doctor_patient.search'),
  ('doctor', 'lab_request.create'),
  ('admin', 'lab_result.read'),
  ('doctor', 'lab_result.read'),
  ('patient', 'lab_result.read'),
  ('doctor', 'lab_result.write'),
  ('patient', 'lesion_episode.create'),
  ('patient', 'lesion_episode.delete'),
  ('admin', 'lesion_episode.read'),
  ('doctor', 'lesion_episode.read'),
  ('patient', 'lesion_episode.read'),
  ('patient', 'lesion_episode.read_own'),
  ('admin', 'lesion_episode.read_record'),
  ('doctor', 'lesion_episode.read_record'),
  ('patient', 'lesion_episode.update'),
  ('patient', 'lesion_location.create'),
  ('patient', 'lesion_location.delete'),
  ('admin', 'lesion_location.read'),
  ('doctor', 'lesion_location.read'),
  ('patient', 'lesion_location.read'),
  ('patient', 'lesion_location.update'),
  ('patient', 'lesion_photo.create'),
  ('patient', 'lesion_photo.delete'),
  ('admin', 'lesion_photo.read'),
  ('doctor', 'lesion_photo.read'),
  ('patient', 'lesion_photo.read'),
  ('patient', 'lesion_photo.update'),
  ('admin', 'media.delete'),
  ('doctor', 'media.delete'),
  ('patient', 'media.delete'),
  ('admin', 'media.read'),
  ('doctor', 'media.read'),
  ('patient', 'media.read'),
  ('doctor', 'media.upload'),
  ('patient', 'media.upload'),
  ('doctor', 'medical_record.accept'),
  ('admin', 'medical_record.answer.read'),
  ('doctor', 'medical_record.answer.read'),
  ('patient', 'medical_record.answer.read'),
  ('doctor', 'medical_record.answer.write'),
  ('patient', 'medical_record.answer.write'),
  ('doctor', 'medical_record.classify'),
  ('patient', 'medical_record.classify'),
  ('doctor', 'medical_record.complete'),
  ('doctor', 'medical_record.create'),
  ('patient', 'medical_record.create'),
  ('admin', 'medical_record.delete'),
  ('admin', 'medical_record.history'),
  ('doctor', 'medical_record.history'),
  ('patient', 'medical_record.history'),
  ('admin', 'medical_record.list'),
  ('doctor', 'medical_record.list'),
  ('admin', 'medical_record.read'),
  ('doctor', 'medical_record.read'),
  ('patient', 'medical_record.read'),
  ('admin', 'permission.create'),
  ('admin', 'permission.delete'),
  ('admin', 'permission.list'),
  ('admin', 'permission.update'),
  ('admin', 'permission_endpoint.assign'),
  ('admin', 'permission_endpoint.read'),
  ('admin', 'permission_endpoint.revoke'),
  ('doctor', 'prescription.create'),
  ('admin', 'prescription.read'),
  ('doctor', 'prescription.read'),
  ('patient', 'prescription.read'),
  ('admin', 'profile.read'),
  ('doctor', 'profile.read'),
  ('patient', 'profile.read'),
  ('admin', 'profile.update'),
  ('doctor', 'profile.update'),
  ('patient', 'profile.update'),
  ('admin', 'role.create'),
  ('admin', 'role.delete'),
  ('admin', 'role.list'),
  ('admin', 'role.update'),
  ('admin', 'role_permission.assign'),
  ('admin', 'role_permission.read'),
  ('admin', 'role_permission.revoke'),
  ('admin', 'room.create'),
  ('admin', 'room.delete'),
  ('admin', 'room.read'),
  ('doctor', 'room.read'),
  ('admin', 'room.update'),
  ('admin', 'template.create'),
  ('admin', 'template.delete'),
  ('admin', 'template.question.create'),
  ('admin', 'template.question.delete'),
  ('admin', 'template.question.update'),
  ('admin', 'template.read'),
  ('doctor', 'template.read'),
  ('patient', 'template.read'),
  ('admin', 'template.section.create'),
  ('admin', 'template.section.delete'),
  ('admin', 'template.section.update'),
  ('admin', 'template.update'),
  ('patient', 'uas7.create'),
  ('patient', 'uas7.eligibility'),
  ('admin', 'uas7.read'),
  ('doctor', 'uas7.read'),
  ('patient', 'uas7.read'),
  ('admin', 'user.assign'),
  ('admin', 'user.create'),
  ('admin', 'user.delete'),
  ('admin', 'user.list'),
  ('admin', 'user.read'),
  ('admin', 'user.update')
) AS v(role, perm)
JOIN roles r ON r.name = v.role
JOIN permissions p ON p.name = v.perm
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- Tài khoản admin đầu tiên (chưa gắn chi nhánh/khoa/phòng; admin không cần staffs)
-- Đăng nhập: phone 0900000000 / mật khẩu Admin@123  (ĐỔI NGAY sau khi demo)
INSERT INTO users (full_name, phone, password_hash, gender, role_id)
SELECT 'System Admin', '0900000000', '$2b$10$JaNPz4uygKMcL2/x3vtWO.gSp76Ll8u77sv4CZFe74rYDahrpDzlW', 'other', role_id FROM roles WHERE name = 'admin'
ON CONFLICT (phone) DO NOTHING;

COMMIT;
